name: Deploy to Amazon ECS Cluster on Staging
on:
  push:
    branches:
      - main
env:
  ENVIRONMENT: staging

jobs:
  tests:
    uses: ./.github/workflows/pytest_workflow.yml
    with:
      ENVIRONMENT: staging
      STAGING_API_URL: https://api.staging.mypersonas.ai
      STAGING_FRONTEND_URL: https://manage.staging.mypersonas.ai
      STAGING_WEBSOCKET_URL: wss://websocket-chat.staging.mypersonas.ai
      STAGING_RTC_URL: https://rtc.staging.mypersonas.ai
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      JIVE_ADDON_CLIENT_ID: ${{ secrets.JIVE_ADDON_CLIENT_ID }}
      JIVE_ADDON_CLIENT_SECRET: ${{ secrets.JIVE_ADDON_CLIENT_SECRET }}
      ENCRYPTION_ALGORITHM_SECRET_KEY: ${{ secrets.ENCRYPTION_ALGORITHM_SECRET_KEY }}
